defaults: &defaults
  docker:
    - image: billyboingo/circleci-node-awscli
  working_directory: ~/cutwater
  parallelism: 1
  shell: /bin/bash --login

aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &install yarn --no-progress --frozen-lockfile
  - &timezone
      name: 'Set Pacific Time Zone'
      command: "echo 'America/Los_Angeles' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata;"

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *timezone
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          name: 'Build'
          command: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build
