defaults: &defaults
  docker:
    - image: billyboingo/circleci-node-awscli
  working_directory: ~/cutwater
  parallelism: 1
  shell: /bin/bash --login

aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &install yarn --no-progress --frozen-lockfile
  - &timezone
      name: 'Set Pacific Time Zone'
      command: "echo 'America/Los_Angeles' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata;"

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: *timezone
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          name: 'Lint'
          command: yarn ci:lint
      - store_test_results:
          path: reports/junit

  test:
    <<: *defaults
    steps:
      - checkout
      - run: *timezone
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          name: 'Run Tests'
          command: yarn ci:test
      - store_test_results:
          path: reports/junit

  deploy-site:
    <<: *defaults
    steps:
      - checkout
      - run: *timezone
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          name: 'Generate API Docs'
          command: yarn ci:docs
      - run:
          name: 'Deploying to GitHub Pages'
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_NAME"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=$GIT_USER yarn run publish-gh-pages

workflows:
  version: 2
  lint-test-doc:
    jobs:
      - lint
      - test
      - deploy-site
          filters: *filter-ignore-gh-pages
