defaults: &defaults
  docker:
    - image: billyboingo/circleci-node-awscli

  working_directory: ~/cutwater
  parallelism: 1
  shell: /bin/bash --login

aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 'Set Pacific Time Zone'
          command: "echo 'America/Los_Angeles' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata;"
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run:
          name: 'Run Tests'
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
