swagger: "2.0"
info:
  title: 
    'Test API' 
  description: Test only API.
  version: 2.0.0
schemes:
  - https
paths:
  /api/graphql:
    get:
      produces:
        - application/json
      parameters:
        - name: query
          in: query
          description: The graphql query
          required: true
          type: string
      responses:
        '200': 
          description: The results of the query.
        default: 
          description: Unexpected error.
      x-amazon-apigateway-integration:
        uri: 
          'Fn::Sub': 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GraphqlHandler.Arn}/invocations'
        passthroughBehavior: when_no_match
        httpMethod: post
        type: aws_proxy
