export enum Comparator {
  EQ = 'EQ',
  NE = 'NE',
  LE = 'LE',
  LT = 'LT',
  GE = 'GE',
  GT = 'GT',
  NOT_NULL = 'NOT_NULL',
  NULL = 'NULL',
  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  BEGINS_WITH = 'BEGINS_WITH',
  IN = 'IN',
  BETWEEN = 'BETWEEN',
}
