name: CI

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - uses: aws-actions/setup-sam@v1
    
    - name: Configure Node
      uses: actions/setup-node@v3
      with:
        cache: "yarn"
        node-version: '16'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run:  yarn build
      env:
        NX_BRANCH: ${{ github.ref_name }}
